### ISSUE TITLE
Provide v1.12

### ISSUE THREAD

**Issue by asdfklgash** [maateen/docker-beanstalkd#1]
Since 2020-06-04 there is Version 1.12 from beanstalkd: https://beanstalkd.github.io/2020/06/04/1.12-release-notes.html

Can you provide a Docker image (tag) against that version?

**Comment by maateen** [comment]
@asdfklgash sure. Thanks for opening this issue. I will push the new version next weekend.

**Comment by maateen** [comment]
@asdfklgash I have pushed v1.12 to Docker hub. Please check the updated README.
